COMMENT =		lightweight extensible message format

MODPY_DISTV =		0.6.0
DISTNAME=		lxmf-${MODPY_DISTV}
PKGNAME =		${DISTNAME}

CATEGORIES =		net

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_PYBUILD =		setuptools

RUN_DEPENDS =		net/py-rns

.include <bsd.port.mk>
