# $OpenBSD$

COMMENT =	Parameterized testing with any Python test framework

MODPY_EGG_VERSION =	0.7.4

DISTNAME =	parameterized-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi devel

HOMEPAGE =	https://github.com/wolever/parameterized

# FreeBSD
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =	${MODPY_DEFAULT_VERSION_3}

FLAVORS =		python3
FLAVOR ?=

.include <bsd.port.mk>
